apiVersion: apps/v1
kind: Deployment
metadata:
  name: trendtrove-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trendtrove-app
  template:
    metadata:
      labels:
        app: trendtrove-app
    spec:
      containers:
        - name: app
          image: us-central1-docker.pkg.dev/canaryguard-bda/canaryguard/trendtrove-app:latest
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: trendtrove-secrets
            - configMapRef:
                name: trendtrove-config
          env:
            - name: AUTH_SERVICE_URL
              value: http://auth-service:3000
            - name: PRODUCT_SERVICE_URL
              value: http://product-service:3000
            - name: CART_SERVICE_URL
              value: http://cart-service:3000
            - name: MAIL_SERVICE_URL
              value: http://mail-service:3000
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: trendtrove-app
  ports:
    - name: http
      port: 3000
      targetPort: 3000
