apiVersion: v1
kind: Secret
metadata:
  name: trendtrove-secrets
type: Opaque
stringData:
  SESSION_SECRET: replace_me
  DATABASE_URL: postgres://postgres:12345678@postgres:5432/ecommerce_dev
  MONGO_URI: mongodb://mongodb:27017/ecommerce_dev
  STRIPE_API_KEY: sk_test_xxx
  GOOGLE_CLIENT_ID: replace_me
  GOOGLE_CLIENT_SECRET: replace_me
  MAILER_USER: you@example.com
  MAILER_PASSWORD: app_password
